### ISSUE TITLE
Experimental rerun expiration

### ISSUE THREAD

**Issue by ErikaKriks** [arsentievalex/streamlit-dynamic-filters#3]
Please replace `st.experimental_rerun` with `st.rerun`.

`st.experimental_rerun` will be removed after 2024-04-01.

**Comment by arsentievalex** [comment]
@ErikaKriks thanks for that! I just replaced it in the new version 0.1.4

**Comment by arsentievalex** [comment]
@ErikaKriks thanks for that! I just replaced it in the new version 0.1.4
