### ISSUE TITLE
Reset all filters at once

### ISSUE THREAD

**Issue by johanneswerner** [arsentievalex/streamlit-dynamic-filters#4]
Is there a possibility to reset all filters at once? I would like to add a button on the sidebar below the filters to reset all filters.

**Comment by arsentievalex** [comment]
you can achieve this by clearing the session state. See an example below:


```
def clear_cache():
    keys = list(st.session_state.keys())
    for key in keys:
        st.session_state.pop(key)

st.button('Reset filters', on_click=clear_cache)
```
