### ISSUE TITLE
Hide filters on one page in multi-page app

### ISSUE THREAD

**Issue by johanneswerner** [arsentievalex/streamlit-dynamic-filters#5]
Is it possible to hide the sidebar on one page of a multipage app? I would like to not show the filters on the entry page of my app. 

This seems to be done in your app: https://dynamic-filters-demo.streamlit.app/

Thank you!

**Comment by arsentievalex** [comment]
Hi @johanneswerner if I understand your question correctly, you can just add the st.sidebar() to the second page of your app, since each page is a separate .py file. I believe the [Streamlit forum](https://discuss.streamlit.io/) will be a better place for such questions. Thanks!
