### ISSUE TITLE
Sorting of columns individually

### ISSUE THREAD

**Issue by johanneswerner** [arsentievalex/streamlit-dynamic-filters#8]
I have a few columns in my dataframe that I would like to sort individually (one mixedsort: 1mg - 3mg - 10mg, the rest alphabetically, however each column should be sorted alphabetically) - is there a possibility to apply the sorting that all dropdown menus are sorted in themselves (even if this is not the order that appears in the dataframe input for a respective column)?

Thank you!

**Comment by arsentievalex** [comment]
I added alphabetical sorting by default in the new version. Please use pip install streamlit-dynamic-filters==0.1.6

**Comment by johanneswerner** [comment]
It is a while, but thank you for that. Can I apply custom (e.g. mixedsort) for some of the columns? One of my columns has units, i.e. "100 mg" appears before "25 mg" with automatic sorting.
